# Site Settings
title: Marco Cardia | Ph.D. PostDoc
description: >-
  Personal academic and research portfolio.
  Exploring Machine Learning for environmental science and digital accessibility.
author: Marco Cardia
github_username: cardiamc
linkedin_username: marco-cardia

remote_theme: pages-themes/tactile@v0.2.0

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

google_analytics: G-WK62NLLH2X